import type { Metadata } from "next";
import { Roboto_Serif, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const rbotoSerif = Roboto_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Licență Ciocan Sebastian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rbotoSerif.variable} ${spaceGrotesk.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
